#Ledges created by sudologic

#worldname
world: world

#Spawn settings
useWorldSpawn: true
#If useWorldSpawn is false, players will be sent to these coordinates instead:
spawnX: 0
spawnY: 80
spawnZ: 0

#Controls how far players should fall before being teleported back to the spawnpoint.
#Will NOT prevent void damage, recommend values HIGHER than zero.
floor: 0