main: me.sudologic.ledges.Main
name: LedgesRevived
description: Ledges minigame by sudologic
version: 1.1
author: sudologic
api-version: 1.18
commands:
  ShowLeaderboard:
    description: Displays the leaderboard
    usage: /ShowLeaderboard